server:
  port: 8091 #服务端口
eureka:
  client:
    fetch-registry: false #是否从eureka获取注册信息
    register-with-eureka: false #是否注册到eureka
    service-url:  #客户端与Eureka服务端进行交互的地址
      defaultZone: http://192.168.1.13:8091/eureka/
  server:
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 30000 #服务注册表清理间隔（单位毫秒，默认是30*1000)
